# For more info on HTTP files go to https://aka.ms/vs/httpfile
@apiUrl=https://localhost:1338

# Members of the Software Center can add new items to our catalog of supported software.
# We have a "COLLECTION" of supported software, and we want to APPEND a new subordinate resource (DOCUMENT) to that collection.

POST {{apiUrl}}/catalog
Content-Type: application/json

{
  "title": "Visual Studio",
  "description": "An Integrated Development Environment for .NET Developer son Windows"
}

###

GET {{apiUrl}}/catalog

###

GET {{apiUrl}}/catalog/920bf506-407a-430a-bd08-591f41995622